server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnastasiaUrupa/config-repo.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

