server:
  port: 8888
  shutdown: graceful
spring:
  application:
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AnastasiaUrupa/config-repo.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

